# cPanel Deployment Configuration for Parish Management System
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/shemidig/parish_system/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.gitignore
    - cd $DEPLOYPATH && php artisan optimize:clear
    - cd $DEPLOYPATH && php artisan key:generate --force
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan storage:link
    - cd $DEPLOYPATH && php artisan db:configure-production
    - cd $DEPLOYPATH && php artisan db:optimize-mysql
    - cd $DEPLOYPATH && chmod -R 755 storage bootstrap/cache
    - cd $DEPLOYPATH && chmod 644 .env
    - cd $DEPLOYPATH && php artisan db:seed --class=UserSeeder --force --no-interaction
