# Ultra-Fast cPanel Deployment - Parish Management System
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/shemidig/parish_system/
    - rsync -av --exclude='node_modules' --exclude='.git' --exclude='tests' --exclude='storage/logs' --exclude='storage/framework/cache' --exclude='storage/framework/sessions' --exclude='storage/framework/views' . $DEPLOYPATH/
    - /bin/cp .env $DEPLOYPATH/
    - cd $DEPLOYPATH && php artisan key:generate --force
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan storage:link
    - cd $DEPLOYPATH && chmod -R 755 storage bootstrap/cache
