#!/bin/bash
##############################################################################
# PRODUCTION GIT CLEANUP SCRIPT
##############################################################################
# This script fixes git conflicts on production server
# Run this on your production server via cPanel Terminal
##############################################################################

echo "=========================================="
echo "Production Git Cleanup Script"
echo "=========================================="
echo ""

# Navigate to deployment directory
cd /home2/shemidig/parish_system || exit 1

echo "Current directory: $(pwd)"
echo ""

# Step 1: Backup current webhook.php if it exists
echo "=== Step 1: Backup existing webhook.php ==="
if [ -f "public/webhook.php" ]; then
    cp public/webhook.php public/webhook.php.backup.$(date +%Y%m%d_%H%M%S)
    echo "✓ Backed up existing webhook.php"
else
    echo "No existing webhook.php to backup"
fi
echo ""

# Step 2: Stash or discard local changes
echo "=== Step 2: Reset git repository ==="
echo "This will discard changes in node_modules and vendor (they're auto-generated)"

# Reset any tracked files
git reset --hard HEAD
echo "✓ Reset tracked files"

# Remove untracked files in public/build (auto-generated by Vite)
if [ -d "public/build" ]; then
    rm -rf public/build
    echo "✓ Removed auto-generated public/build"
fi

# Remove the old webhook.php (will be replaced by git pull)
if [ -f "public/webhook.php" ]; then
    rm -f public/webhook.php
    echo "✓ Removed old webhook.php"
fi

echo ""

# Step 3: Pull latest code from GitHub
echo "=== Step 3: Pull latest code from GitHub ==="
git pull origin Main
echo ""

# Step 4: Verify critical files exist
echo "=== Step 4: Verify critical files ==="
CRITICAL_FILES=(
    "public/webhook.php"
    "public/deploy.php"
)

for file in "${CRITICAL_FILES[@]}"; do
    if [ -f "$file" ]; then
        size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
        echo "✓ $file ($size bytes)"
        
        # Set correct permissions
        chmod 644 "$file"
        echo "  ✓ Set permissions to 644"
    else
        echo "✗ MISSING: $file"
    fi
done
echo ""

# Step 5: Install/update dependencies
echo "=== Step 5: Update dependencies ==="
echo "Installing Composer dependencies..."
composer install --no-dev --optimize-autoloader --no-interaction 2>&1 | tail -5
echo ""

echo "Installing NPM dependencies..."
npm install --production=false 2>&1 | tail -5
echo ""

# Step 6: Build assets
echo "=== Step 6: Build frontend assets ==="
npm run build 2>&1 | tail -10
echo ""

# Step 7: Optimize Laravel
echo "=== Step 7: Optimize Laravel ==="
php artisan config:cache
php artisan route:cache
php artisan view:cache
echo "✓ Laravel optimized"
echo ""

# Step 8: Check webhook secret
echo "=== Step 8: Verify webhook configuration ==="
EXPECTED_SECRET="7c405eeeaca081e63d0fd443c7f564b1719bf0594169601aa2a706cbea276a8a"

if grep -q "$EXPECTED_SECRET" public/webhook.php; then
    echo "✓ Webhook secret is correct"
else
    echo "✗ WARNING: Webhook secret not found or incorrect!"
    echo "  Expected: $EXPECTED_SECRET"
fi

if grep -q "$EXPECTED_SECRET" public/deploy.php; then
    echo "✓ Deploy secret is correct"
else
    echo "✗ WARNING: Deploy secret not found or incorrect!"
fi
echo ""

# Step 9: Set final permissions
echo "=== Step 9: Set final permissions ==="
chmod -R 755 storage bootstrap/cache
chmod -R 644 public/*.php
chmod 644 .env
echo "✓ Permissions set"
echo ""

echo "=========================================="
echo "✓ Production setup complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Test webhook at: https://parish.quovadisyouthhub.org/webhook.php"
echo "2. Go to GitHub webhook settings and click 'Redeliver'"
echo "3. Should return 200 OK and trigger deployment"
echo ""
echo "Monitor logs:"
echo "  tail -f storage/logs/webhook.log"
echo "  tail -f storage/logs/deployment.log"
echo ""
